//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceTest.ModeloWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modelo", Namespace="http://schemas.datacontract.org/2004/07/WS_MiPrepago.Dominio")]
    [System.SerializableAttribute()]
    public partial class Modelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fec_fabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int marca_marca_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int modelo_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fec_fab {
            get {
                return this.fec_fabField;
            }
            set {
                if ((object.ReferenceEquals(this.fec_fabField, value) != true)) {
                    this.fec_fabField = value;
                    this.RaisePropertyChanged("fec_fab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int marca_marca_id {
            get {
                return this.marca_marca_idField;
            }
            set {
                if ((this.marca_marca_idField.Equals(value) != true)) {
                    this.marca_marca_idField = value;
                    this.RaisePropertyChanged("marca_marca_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int modelo_id {
            get {
                return this.modelo_idField;
            }
            set {
                if ((this.modelo_idField.Equals(value) != true)) {
                    this.modelo_idField = value;
                    this.RaisePropertyChanged("modelo_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloRepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WS_MiPrepago.Errores")]
    [System.SerializableAttribute()]
    public partial class ModeloRepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marca_marca_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelo_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca_marca_id {
            get {
                return this.marca_marca_idField;
            }
            set {
                if ((object.ReferenceEquals(this.marca_marca_idField, value) != true)) {
                    this.marca_marca_idField = value;
                    this.RaisePropertyChanged("marca_marca_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo_id {
            get {
                return this.modelo_idField;
            }
            set {
                if ((object.ReferenceEquals(this.modelo_idField, value) != true)) {
                    this.modelo_idField = value;
                    this.RaisePropertyChanged("modelo_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionGeneral", Namespace="http://schemas.datacontract.org/2004/07/WS_MiPrepago.Errores")]
    [System.SerializableAttribute()]
    public partial class ExceptionGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModeloWS.ISmodelo")]
    public interface ISmodelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/crearModelo", ReplyAction="http://tempuri.org/ISmodelo/crearModeloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFServiceTest.ModeloWS.ModeloRepetidoException), Action="http://tempuri.org/ISmodelo/crearModeloModeloRepetidoExceptionFault", Name="ModeloRepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WS_MiPrepago.Errores")]
        WCFServiceTest.ModeloWS.Modelo crearModelo(WCFServiceTest.ModeloWS.Modelo marcaACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/crearModelo", ReplyAction="http://tempuri.org/ISmodelo/crearModeloResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo> crearModeloAsync(WCFServiceTest.ModeloWS.Modelo marcaACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/obtenerModelo", ReplyAction="http://tempuri.org/ISmodelo/obtenerModeloResponse")]
        WCFServiceTest.ModeloWS.Modelo obtenerModelo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/obtenerModelo", ReplyAction="http://tempuri.org/ISmodelo/obtenerModeloResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo> obtenerModeloAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/listarModelo", ReplyAction="http://tempuri.org/ISmodelo/listarModeloResponse")]
        WCFServiceTest.ModeloWS.Modelo[] listarModelo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/listarModelo", ReplyAction="http://tempuri.org/ISmodelo/listarModeloResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> listarModeloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/Listar_ModeloxMarca", ReplyAction="http://tempuri.org/ISmodelo/Listar_ModeloxMarcaResponse")]
        WCFServiceTest.ModeloWS.Modelo[] Listar_ModeloxMarca(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/Listar_ModeloxMarca", ReplyAction="http://tempuri.org/ISmodelo/Listar_ModeloxMarcaResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> Listar_ModeloxMarcaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/Listado_ModeloxMarca_Proveedor", ReplyAction="http://tempuri.org/ISmodelo/Listado_ModeloxMarca_ProveedorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFServiceTest.ModeloWS.ExceptionGeneral), Action="http://tempuri.org/ISmodelo/Listado_ModeloxMarca_ProveedorExceptionGeneralFault", Name="ExceptionGeneral", Namespace="http://schemas.datacontract.org/2004/07/WS_MiPrepago.Errores")]
        WCFServiceTest.ModeloWS.Modelo[] Listado_ModeloxMarca_Proveedor(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmodelo/Listado_ModeloxMarca_Proveedor", ReplyAction="http://tempuri.org/ISmodelo/Listado_ModeloxMarca_ProveedorResponse")]
        System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> Listado_ModeloxMarca_ProveedorAsync(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmodeloChannel : WCFServiceTest.ModeloWS.ISmodelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmodeloClient : System.ServiceModel.ClientBase<WCFServiceTest.ModeloWS.ISmodelo>, WCFServiceTest.ModeloWS.ISmodelo {
        
        public SmodeloClient() {
        }
        
        public SmodeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmodeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmodeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmodeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServiceTest.ModeloWS.Modelo crearModelo(WCFServiceTest.ModeloWS.Modelo marcaACrear) {
            return base.Channel.crearModelo(marcaACrear);
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo> crearModeloAsync(WCFServiceTest.ModeloWS.Modelo marcaACrear) {
            return base.Channel.crearModeloAsync(marcaACrear);
        }
        
        public WCFServiceTest.ModeloWS.Modelo obtenerModelo(int Id) {
            return base.Channel.obtenerModelo(Id);
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo> obtenerModeloAsync(int Id) {
            return base.Channel.obtenerModeloAsync(Id);
        }
        
        public WCFServiceTest.ModeloWS.Modelo[] listarModelo() {
            return base.Channel.listarModelo();
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> listarModeloAsync() {
            return base.Channel.listarModeloAsync();
        }
        
        public WCFServiceTest.ModeloWS.Modelo[] Listar_ModeloxMarca(int id) {
            return base.Channel.Listar_ModeloxMarca(id);
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> Listar_ModeloxMarcaAsync(int id) {
            return base.Channel.Listar_ModeloxMarcaAsync(id);
        }
        
        public WCFServiceTest.ModeloWS.Modelo[] Listado_ModeloxMarca_Proveedor(string nombre) {
            return base.Channel.Listado_ModeloxMarca_Proveedor(nombre);
        }
        
        public System.Threading.Tasks.Task<WCFServiceTest.ModeloWS.Modelo[]> Listado_ModeloxMarca_ProveedorAsync(string nombre) {
            return base.Channel.Listado_ModeloxMarca_ProveedorAsync(nombre);
        }
    }
}
